services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # Map Vite's development port to the host's port 3000
    volumes:
      - .:/app # Bind mount the project directory for live updates
      - /app/node_modules # Prevent overwriting node_modules in the container
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes in Docker
    stdin_open: true
    tty: true
    restart: unless-stopped